src/apis/login.js, src/pages/login/Login.jsx, src/router.jsx
=> [Test]-로그인 페이지 APi test

index.html, package-lock.json, package.json, src/apis/login.js, src/apis/signUp.js, src/constants/signUp.js, src/pages/signUp/NuguCreate.jsx, src/pages/signUp/_hooks/useSignUp.js
회원가입 / 로그인 API 연결을 완료했고, 로그인 시 토큰을 쿠키에 저장하도록 했습니다.
- #31
=> [Feature] #31 - 로그인 / 회원가입 API 연결 및 토큰 처리

package-lock.json, src/apis/login.js, src/apis/nuguIntro.js, src/components/common/introField/IntroField.jsx, src/pages/nuguIntro/NuguIntro.jsx, src/pages/nuguIntro/WriteIntro.jsx, src/pages/nuguIntro/_hooks/useIntroForm.js
>누구소개 페이지 list조회, 누구 소개 작성 ( 소유자, 접속자뷰) API 연결했습니다.
누구 작성에서 키워드 추출하기 위해 커스텀 훅 제작했습니다.
```javascript
export const getIntroList = async () => {
try {
const token = Cookies.get("access_token");
if (token) {
const response = await instance.get("/intro");
console.log("getIntroList", response);
} else {
const uuid = crypto.randomUUID();
console.log("getIntroList 접속자", uuid);
const response = await instance.get(`/intro/${uuid}`);
console.log("getGuestIntroList", response);
}
} catch (error) {
throw error;
}
};
```
첨부된 코드 처럼 token이 없을 때 uuid를 발급 받아 다른 경로로 API 요청 보내도록 구현했습니다..! 
다른 더 좋은 방법이 있다면 편하게 말씀해주세요! :)
-  #25
=> [Feature]- 누구소개 페이지 API 연결

src/apis/login.js
>useNavigate 위치  훅 안으로 변경했습니다.
- ex) #25
=> [Fix]- useNavigate 위치 훅 안으로 변경

src/apis/instance.js, src/apis/nuguInfo.js, src/apis/uuid.js, src/pages/login/Login.jsx, src/pages/nugu/NuguAdmin.jsx, src/pages/nugu/_hooks/useNuguInfo.js, src/router.jsx
"누구" 페이지 API 연결을 완료했습니다.
Admin View와 Guest View를 구분하기 위한 로직을 구현하여 화면을 구분했습니다.
Admim
Guest
로그인 시 uuid를 획득하여, uuid 기반 공유가 가능하도록 쿠기에 설정하고 있습니다. 
참고하셔서 다른 페이지에도 반영 부탁드려요!
```js
import { instance } from "./instance";
import Cookies from "js-cookie";
export const getUUID = async () => {
try {
const response = await instance.get("/user/uuid");
const uuid = response.data;
if (uuid) {
Cookies.set("uuid", uuid, {
path: "/",
secure: true,
sameSite: "Strict",
});
}
} catch (err) {
throw err;
}
};
```
- #33
=> [Feature] #33 - 누구 페이지 API 연결

src/apis/login.js, src/pages/login/Login.jsx, src/pages/nugu/Nugu.jsx, src/router.jsx
=> [Fix] - 로그인 에러 해결

src/apis/login.js, src/apis/nuguIntro.js, src/pages/nuguIntro/NuguIntro.jsx, src/pages/nuguIntro/WriteIntro.jsx, src/pages/onBoarding/styled.js, src/router.jsx
=> [Feature]-누구 소개 페이지 API 연결

src/pages/nuguIntro/NuguIntro.jsx, src/pages/nuguIntro/WriteIntro.jsx
post 완료 전 전 페이지로 이동하는 에러 수정했습니다.
- #25
=> [Fix]- post 완료 전 라우팅 수정

src/components/rankingBox/RankingBox.jsx, src/pages/nuguIntro/NuguIntro.jsx
>누구소개 API 연결: get 해온 data 처리했습니다.
- #25
=> [Fix]- 누구소개 API 연결: get 해온 data 처리

src/components/rankingBox/RankingBox.jsx, src/pages/nuguIntro/NuguIntro.jsx
>누구 소개 introList 에 값이 있을 때만 Object.key 사용하도록 수정했습니다.
- #25
=> [Fix]- 누구 소개 introList 예외처리

src/apis/instance.js, src/apis/nuguTest.js, src/atoms/nuguTestState.js, src/components/nuguTest/NuguTestTrue.jsx, src/pages/nuguTest/NuguTest.jsx
누구 테스트 소유자 뷰 응시자 확인 API를 연동했습니다.
누구 테스트 소유자 뷰 생성 유무 API를 연동 연동했습니다.
- 테스트를 생성하지 않은 경우
- 테스트 생성 후 참가자가 없는 경우
- 테스트 생성 후 참가자가 있는 경우
- #41
=> [Feature] #41 - 누구테스트 소유자 API 연동 (get)

src/apis/nuguPatch.js, src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/useNuguPatch.js
>누구 수정: patch 전 정보 /user 에 get요청 보내서 정보 받아오도록 수정했습니다.
-  #54
=> [Fix]- 누구 수정: patch 전 정보 가져오기 수정

src/hooks/useForm.js, src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/usePatchChip.js
=> [Fix]- 누구 수정:기존 선택 칩 들고 오기

src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/usePatchChip.js
>누구 수정:회원가입 시 선택된 키워드 들고오기
- #54
=> [Fix]-누구 수정:회원가입 시 선택된 키워드 들고오기

src/apis/nuguPatch.js, src/pages/login/Login.jsx, src/pages/login/styled.js, src/pages/nuguIntro/WriteIntro.jsx, src/pages/nuguIntro/styled.js, src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/styled.js, src/pages/onBoarding/styled.js
>누구 수정 인스타 주소 중 아이디만 받아오기
- #66
=> Fix- 누구 수정 인스타 주소 중 아이디만 받아오기

src/apis/nuguTest.js, src/components/nuguTestRanking/NonRankingBox.jsx, src/components/nuguTestRanking/NuguTestRanking.jsx, src/pages/nuguTest/ChallengerTest.jsx, src/pages/nuguTest/_hooks/useChallengeTest.js
>누구 테스트 소유자 정답 get API 연결
- #66
=> [Feature]- 누구 테스트 소유자 정답 get API 연결

src/pages/nuguTest/ChallengerTest.jsx, src/pages/nuguTest/NuguChallenge.jsx
>누구테스트 응시자, 소유자 답비교 콘솔 test
- #66
=> [Test]- 누구테스트 응시자, 소유자 답비교 콘솔 test

src/components/testQuestion/TestQuestion.jsx, src/pages/nuguTest/ChallengerTest.jsx
>isAnswerinCorrect 예외처리 및 한번 답 선택 시 수정 불가 기능 구현
- #66
=> [Feature]- isAnswerinCorrect 예외처리 및 한번 답 선택 시 수정 불가 기능 구현

src/components/testQuestion/TestQuestion.jsx, src/pages/nuguTest/ChallengerTest.jsx
>누구테스트 선택 박스 색상 수정했습니다.
-  #66
=> [Fix]-누구테스트 선택 박스 색상 수정

src/hooks/useForm.js, src/pages/login/Login.jsx, src/pages/login/styled.js, src/pages/nuguTest/ChallengerTest.jsx, src/pages/signUp/SignUp.jsx, src/pages/signUp/_hooks/useSignUp.js, src/pages/signUp/styled.js
>로그인, 회원가입 유효성 검사 구현했습니다.
- #66
=> [Feature]- 로그인, 회원가입 유효성 검사 구현

src/pages/nuguTest/ChallengerTest.jsx
>isAnswerinCorrect 값 test
-  #66
=> [Test]- isAnswerinCorrect 값 test

src/pages/nuguTest/ChallengerTest.jsx
=> [Test]- 누구 테스트 정답 비교 로직 test

src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/useNuguPatch.js, src/pages/nuguPatch/styled.js, src/pages/nuguTest/ChallengerTest.jsx, src/pages/nuguTest/NuguChallenge.jsx
=> [Feature]- 누구 수정 유효성 검사 추가

src/apis/nuguTest.js, src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/useNuguPatch.js, src/pages/nuguTest/NuguChallenge.jsx
>접속자가 누구테스트에 접속 하였을 때 소유자의 누구테스트 응시 여부를 가져와 그에 따라 다른 컴포넌트가 보이도록 API 연동했습니다.
-  #66
=> [Feature]- 접속자뷰: 소유자의 누구테스트 응시 여부 API 연결

src/components/error/Error.jsx, src/components/toast/Toast.jsx, src/hooks/useToast.js, src/pages/login/Login.jsx, src/pages/signUp/NuguCreate.jsx
각 에러 케이스에 맞게 신규 UI/UX를 추가했습니다.
- 로그인 실패 시
- 동일 아이디 존재 시
- #98
=> [Fix] #98 - 로그인 / 회원가입 에러 처리

src/apis/nuguPatch.js, src/components/testQuestion/styled.js, src/pages/nuguIntro/WriteIntro.jsx, src/pages/nuguIntro/styled.js, src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/useNuguPatch.js, src/pages/nuguPatch/styled.js, src/pages/signUp/styled.js
=> [Fix]- 누구 소개 인스타 url 수정

src/components/common/introField/styled.js, src/pages/nuguIntro/WriteIntro.jsx
>누구 수정: 150자 넘어갈 경우 버튼 비활성화
- #66
=> [Fix]-누구 수정: 150자 넘어갈 경우 버튼 비활성화

src/pages/nuguPatch/NuguPatch.jsx, src/pages/nuguPatch/_hooks/useNuguPatch.js
=> [Fix]-인스타  url 에러 픽스

src/components/testQuestion/TestQuestion.jsx, src/pages/nuguTest/MakeNuguTest.jsx
>isAnswerSelected 전달 props 전달
-  #66
=> [Test]- isAnswerSelected 전달 props 전달

src/components/testQuestion/TestQuestion.jsx, src/pages/nuguTest/ChallengerTest.jsx, src/pages/nuguTest/MakeNuguTest.jsx
>소유자 여부에 따라 answerBox 비활성화 로직 추가
- #66
=> [Fix]- 소유자 여부에 따라 answerBox 비활성화 로직 추가
